baseURL: https://stemangiola.github.io/tidytranscriptomics/
languageCode: en
defaultContentLanguage: en
title: Tidy transcriptomics
preserveTaxonomyNames: yes
enableRobotsTXT: yes
enableEmoji: yes
theme: hugo-theme-even
enableGitInfo: no
pygmentsOptions: linenos=table
pygmentsCodefences: yes
pygmentsUseClasses: yes
pygmentsCodefencesGuessSyntax: yes
hasCJKLanguage: yes
paginate: 5
disqusShortname: ''
googleAnalytics: ''
copyright: ''
author:
  name: Stefano Mangiola, Maria Doyle
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: archives
      name: Archives
      url: /post/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 40
params:
  archivePaginate: 50
  autoCollapseToc: no
  baiduAnalytics: ''
  baiduPush: no
  baiduVerification: ''
  busuanzi:
    enable: no
    pagePV: yes
    sitePV: yes
    siteUV: yes
  changyanAppid: ''
  changyanAppkey: ''
  contentCopyright: ''
  customCSS: []
  customJS: []
  dateFormatToUse: '2006-01-02'
  debug: no
  description: Blog about my research.
  fancybox: yes
  flowchartDiagrams:
    enable: no
    options: ''
  gitRepo: ''
  gitalk:
    clientId: ''
    clientSecret: ''
    owner: ''
    repo: ''
  gitment:
    clientId: ''
    clientSecret: ''
    owner: ''
    repo: ''
  googleVerification: ''
  highlightInClient: no
  keywords:
    - Hugo
    - theme
    - even
  linkToMarkDown: no
  livereUID: ''
  logoTitle: Research blog
  mathjax: no
  mathjaxEnableAutoNumber: no
  mathjaxEnableSingleDollar: no
  mathjaxUseLocalFiles: no
  moreMeta: no
  outdatedInfoWarning:
    enable: no
    hint: 30
    warn: 180
  postMetaInFooter: yes
  publicCDN:
    enable: yes
    fancyboxCSS: <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css"
      integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">
    fancyboxJS: <script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js"
      integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>
    flowchartDiagramsJS: <script src="https://cdn.jsdelivr.net/npm/raphael@2.2.7/raphael.min.js"
      integrity="sha256-67By+NpOtm9ka1R6xpUefeGOY8kWWHHRAKlvaTJ7ONI=" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/flowchart.js@1.8.0/release/flowchart.min.js"
      integrity="sha256-zNGWjubXoY6rb5MnmpBNefO0RgoVYfle9p0tvOQM+6k=" crossorigin="anonymous"></script>
    jquery: <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    sequenceDiagramsCSS: <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.css"
      integrity="sha384-6QbLKJMz5dS3adWSeINZe74uSydBGFbnzaAYmp+tKyq60S7H2p6V7g1TysM5lAaF"
      crossorigin="anonymous">
    sequenceDiagramsJS: <script src="https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js"
      integrity="sha256-4O4pS1SH31ZqrSO2A/2QJTVjTPqVe+jnYgOWUVr7EEc=" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/snapsvg@0.5.1/dist/snap.svg-min.js"
      integrity="sha256-oI+elz+sIm+jpn8F/qEspKoKveTc5uKeFHNNVexe6d8=" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/underscore@1.8.3/underscore-min.js"
      integrity="sha256-obZACiHd7gkOk9iIL/pimWMTJ4W/pBsKu+oZnSeBIek=" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.js"
      integrity="sha384-8748Vn52gHJYJI0XEuPB2QlPVNUkJlJn9tHqKec6J3q2r9l8fvRxrgn/E5ZHV0sP"
      crossorigin="anonymous"></script>
    slideout: <script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js"
      integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>
    timeagoJS: <script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.min.js"
      integrity="sha256-jwCP0NAdCBloaIWTWHmW4i3snUNMHUNO+jr9rYd2iOI=" crossorigin="anonymous"></script>
    timeagoLocalesJS: <script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.locales.min.js"
      integrity="sha256-ZwofwC1Lf/faQCzN7nZtfijVV6hSwxjQMwXL4gn9qU8=" crossorigin="anonymous"></script>
  reward:
    alipay: /path/to/your/alipay-qr-code.png
    enable: no
    wechat: /path/to/your/wechat-qr-code.png
  sequenceDiagrams:
    enable: no
    options: ''
  showArchiveCount: no
  showLanguageSelector: no
  since: '2017'
  social:
    a-email: mailto:mangiolastefano@gmail.com
    b-github: https://github.com/stemangiola
    c-twitter: https://twitter.com/steman_research
  toc: yes
  uglyURLs: no
  utterances:
    owner: ''
    repo: ''
  valine:
    appId: 你的appId
    appKey: 你的appKey
    avatar: mm
    enable: no
    notify: no
    placeholder: 说点什么吧...
    verify: no
    visitor: no
  version: 4.x
privacy:
  googleAnalytics:
    anonymizeIP: yes
  youtube:
    privacyEnhanced: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    startLevel: 1
